title: Introduction to Programming with Python
description: A Tufts University Data Lab Workshop
repo: intro-python
author: Uku-Kaspar Uustalu
slides: intro-python
resources: python
file: intro-python.ipynb
env: intro-python
